ARG os=focal-20230801
FROM ubuntu:${os}

RUN apt-get update && apt-get install -y \
        g++ \
        git \
        make \
        wget \
        ruby ruby-dev \
    && rm -rf /var/lib/apt/lists/*

RUN wget https://apt.puppet.com/puppet7-release-focal.deb && dpkg -i puppet7-release-focal.deb \
    && apt-get update && apt-get install -y \
        puppet-agent \
    && rm -rf /var/lib/apt/lists/*
